# Generated by Django 3.2.5 on 2021-10-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Excerpt', models.CharField(max_length=255)),
                ('Image_Name', models.CharField(max_length=100)),
                ('Date', models.DateField(auto_now=True)),
                ('Slug', models.SlugField(blank=True, default='', max_length=255)),
                ('Content', models.CharField(max_length=500)),
            ],
        ),
    ]
