# Generated by Django 3.2.5 on 2021-12-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='user_name',
        ),
    ]
