# Generated by Django 3.2.5 on 2021-11-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211011_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='caption',
        ),
    ]
